---
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lubelogger
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lubelogger
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    pull_policy: always
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      # test
      UserNameHash: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
      # 1234
      UserPasswordHash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
      EnableAuth: "true"
      POSTGRES_CONNECTION: "Host=postgres;Port=5432;Database=lubelogger;Username=lubelogger;Password=password"
    depends_on:
      - postgres
