--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: app; Type: SCHEMA; Schema: -; Owner: lubelogger
--

CREATE SCHEMA app;


ALTER SCHEMA app OWNER TO lubelogger;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: collisionrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.collisionrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.collisionrecords OWNER TO lubelogger;

--
-- Name: collisionrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.collisionrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.collisionrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extrafields; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.extrafields (
    id integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.extrafields OWNER TO lubelogger;

--
-- Name: gasrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.gasrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.gasrecords OWNER TO lubelogger;

--
-- Name: gasrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.gasrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.gasrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.notes (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.notes OWNER TO lubelogger;

--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: odometerrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.odometerrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.odometerrecords OWNER TO lubelogger;

--
-- Name: odometerrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.odometerrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.odometerrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.planrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.planrecords OWNER TO lubelogger;

--
-- Name: planrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.planrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.planrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planrecordtemplates; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.planrecordtemplates (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.planrecordtemplates OWNER TO lubelogger;

--
-- Name: planrecordtemplates_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.planrecordtemplates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.planrecordtemplates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reminderrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.reminderrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.reminderrecords OWNER TO lubelogger;

--
-- Name: reminderrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.reminderrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.reminderrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicerecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.servicerecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.servicerecords OWNER TO lubelogger;

--
-- Name: servicerecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.servicerecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.servicerecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplyrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.supplyrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.supplyrecords OWNER TO lubelogger;

--
-- Name: supplyrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.supplyrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.supplyrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taxrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.taxrecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.taxrecords OWNER TO lubelogger;

--
-- Name: taxrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.taxrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.taxrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tokenrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.tokenrecords (
    id integer NOT NULL,
    body text NOT NULL,
    emailaddress text NOT NULL
);


ALTER TABLE app.tokenrecords OWNER TO lubelogger;

--
-- Name: tokenrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.tokenrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.tokenrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upgraderecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.upgraderecords (
    id integer NOT NULL,
    vehicleid integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.upgraderecords OWNER TO lubelogger;

--
-- Name: upgraderecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.upgraderecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.upgraderecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: useraccessrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.useraccessrecords (
    userid integer NOT NULL,
    vehicleid integer NOT NULL
);


ALTER TABLE app.useraccessrecords OWNER TO lubelogger;

--
-- Name: userconfigrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.userconfigrecords (
    id integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.userconfigrecords OWNER TO lubelogger;

--
-- Name: userrecords; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.userrecords (
    id integer NOT NULL,
    username text NOT NULL,
    emailaddress text NOT NULL,
    password text NOT NULL,
    isadmin boolean
);


ALTER TABLE app.userrecords OWNER TO lubelogger;

--
-- Name: userrecords_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.userrecords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.userrecords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicles; Type: TABLE; Schema: app; Owner: lubelogger
--

CREATE TABLE app.vehicles (
    id integer NOT NULL,
    data jsonb NOT NULL
);


ALTER TABLE app.vehicles OWNER TO lubelogger;

--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: app; Owner: lubelogger
--

ALTER TABLE app.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: collisionrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.collisionrecords (id, vehicleid, data) FROM stdin;
30	1	{"Id": 30, "Cost": 19.24, "Date": "2021-08-02T00:00:00", "Tags": [], "Files": [], "Notes": "Omix-Ada 18280.18", "Mileage": 215000, "VehicleId": 1, "Description": "Front Bump Stops", "ExtraFields": [], "RequisitionHistory": []}
31	1	{"Id": 31, "Cost": 10.57, "Date": "2021-08-04T00:00:00", "Tags": [], "Files": [], "Notes": "Omix-Ada 53007620", "Mileage": 216400, "VehicleId": 1, "Description": "Cable Guide Assembly", "ExtraFields": [], "RequisitionHistory": []}
32	1	{"Id": 32, "Cost": 11.57, "Date": "2021-08-17T00:00:00", "Tags": [], "Files": [], "Notes": "Gates 21616", "Mileage": 217500, "VehicleId": 1, "Description": "Upper Radiator Hose", "ExtraFields": [], "RequisitionHistory": []}
33	1	{"Id": 33, "Cost": 25.01, "Date": "2021-11-24T00:00:00", "Tags": [], "Files": [], "Notes": "Duralast Gold Thermostat 15359DLG\\nDorman Thermostat Housing 902-306\\nFelpro Thermostat Housing Gasket 35024", "Mileage": 218000, "VehicleId": 1, "Description": "Thermostat", "ExtraFields": [], "RequisitionHistory": []}
34	1	{"Id": 34, "Cost": 131.71, "Date": "2023-07-26T00:00:00", "Tags": [], "Files": [], "Notes": "A/C Compressor\\nEster 100 Refrigerant Oil + O Rings", "Mileage": 221000, "VehicleId": 1, "Description": "R134 Retrofit", "ExtraFields": [], "RequisitionHistory": []}
\.


--
-- Data for Name: extrafields; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.extrafields (id, data) FROM stdin;
\.


--
-- Data for Name: gasrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.gasrecords (id, vehicleid, data) FROM stdin;
105	1	{"Id": 105, "Cost": 31.08, "Date": "2023-07-15T00:00:00", "Tags": [], "Files": [], "Notes": "", "Gallons": 7.951, "Mileage": 222120, "VehicleId": 1, "ExtraFields": [], "IsFillToFull": true, "MissedFuelUp": false}
106	1	{"Id": 106, "Cost": 32.64, "Date": "2023-07-31T00:00:00", "Tags": [], "Files": [], "Notes": "", "Gallons": 8.48, "Mileage": 222241, "VehicleId": 1, "ExtraFields": [], "IsFillToFull": true, "MissedFuelUp": false}
107	1	{"Id": 107, "Cost": 34.16, "Date": "2023-09-15T00:00:00", "Tags": [], "Files": [], "Notes": "", "Gallons": 8.739, "Mileage": 222384, "VehicleId": 1, "ExtraFields": [], "IsFillToFull": true, "MissedFuelUp": false}
108	1	{"Id": 108, "Cost": 38.31, "Date": "2023-10-12T00:00:00", "Tags": [], "Files": [], "Notes": "", "Gallons": 10.057, "Mileage": 222533, "VehicleId": 1, "ExtraFields": [], "IsFillToFull": true, "MissedFuelUp": false}
109	1	{"Id": 109, "Cost": 21.78, "Date": "2023-12-19T00:00:00", "Tags": [], "Files": [], "Notes": "", "Gallons": 7.409, "Mileage": 222647, "VehicleId": 1, "ExtraFields": [], "IsFillToFull": true, "MissedFuelUp": false}
\.


--
-- Data for Name: notes; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.notes (id, vehicleid, data) FROM stdin;
\.


--
-- Data for Name: odometerrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.odometerrecords (id, vehicleid, data) FROM stdin;
1	1	{"Id": 1, "Date": "2022-12-24T00:00:00", "Tags": [], "Files": [], "Notes": "Auto Insert From Gas Record via CSV Import.", "Mileage": 221256, "VehicleId": 1, "ExtraFields": [], "InitialMileage": 221143, "DistanceTraveled": 113}
2	1	{"Id": 2, "Date": "2023-03-24T00:00:00", "Tags": [], "Files": [], "Notes": "Auto Insert From Gas Record via CSV Import.", "Mileage": 221370, "VehicleId": 1, "ExtraFields": [], "InitialMileage": 221256, "DistanceTraveled": 114}
3	1	{"Id": 3, "Date": "2023-04-05T00:00:00", "Tags": [], "Files": [], "Notes": "Auto Insert From Gas Record via CSV Import.", "Mileage": 221466, "VehicleId": 1, "ExtraFields": [], "InitialMileage": 221370, "DistanceTraveled": 96}
4	1	{"Id": 4, "Date": "2023-05-12T00:00:00", "Tags": [], "Files": [], "Notes": "Auto Insert From Gas Record via CSV Import.", "Mileage": 221621, "VehicleId": 1, "ExtraFields": [], "InitialMileage": 221466, "DistanceTraveled": 155}
5	1	{"Id": 5, "Date": "2023-05-29T00:00:00", "Tags": [], "Files": [], "Notes": "Auto Insert From Gas Record via CSV Import.", "Mileage": 221685, "VehicleId": 1, "ExtraFields": [], "InitialMileage": 221621, "DistanceTraveled": 64}
\.


--
-- Data for Name: planrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.planrecords (id, vehicleid, data) FROM stdin;
\.


--
-- Data for Name: planrecordtemplates; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.planrecordtemplates (id, vehicleid, data) FROM stdin;
\.


--
-- Data for Name: reminderrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.reminderrecords (id, vehicleid, data) FROM stdin;
\.


--
-- Data for Name: servicerecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.servicerecords (id, vehicleid, data) FROM stdin;
18	1	{"Id": 18, "Cost": 25.27, "Date": "2021-07-17T00:00:00", "Tags": [], "Files": [], "Notes": "Mopar 090 Filter", "Mileage": 214823, "VehicleId": 1, "Description": "Oil Change", "ExtraFields": [], "RequisitionHistory": []}
19	1	{"Id": 19, "Cost": 22.08, "Date": "2021-08-04T00:00:00", "Tags": [], "Files": [], "Notes": "Changed in Cedar City Walmart Parking Lot", "Mileage": 216464, "VehicleId": 1, "Description": "Oil Change", "ExtraFields": [], "RequisitionHistory": []}
20	1	{"Id": 20, "Cost": 26.43, "Date": "2022-05-06T00:00:00", "Tags": [], "Files": [], "Notes": "The usual.", "Mileage": 219600, "VehicleId": 1, "Description": "Oil Change", "ExtraFields": [], "RequisitionHistory": []}
21	1	{"Id": 21, "Cost": 33.20, "Date": "2023-08-08T00:00:00", "Tags": [], "Files": [], "Notes": "WIX 51085XP Filter", "Mileage": 222242, "VehicleId": 1, "Description": "Oil Change", "ExtraFields": [], "RequisitionHistory": []}
22	1	{"Id": 22, "Cost": 117.17, "Date": "2023-12-15T00:00:00", "Tags": [], "Files": [], "Notes": "EverStart Gr 58", "Mileage": 222500, "VehicleId": 1, "Description": "Battery", "ExtraFields": [], "RequisitionHistory": []}
\.


--
-- Data for Name: supplyrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.supplyrecords (id, vehicleid, data) FROM stdin;
1	1	{"Id": 1, "Cost": 28.83, "Date": "2021-03-05T00:00:00", "Tags": [], "Files": [], "Notes": "Road trip backup", "Quantity": 1, "VehicleId": 1, "PartNumber": "5S1084", "Description": "Crankshaft Position Sensor", "ExtraFields": [], "PartSupplier": "WVE by NTK", "RequisitionHistory": []}
2	1	{"Id": 2, "Cost": 3.19, "Date": "2021-03-08T00:00:00", "Tags": [], "Files": [], "Notes": "1 QT. Spare.", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Motor Oil", "ExtraFields": [], "PartSupplier": "SuperTech", "RequisitionHistory": []}
3	1	{"Id": 3, "Cost": 4.25, "Date": "2021-03-08T00:00:00", "Tags": [], "Files": [], "Notes": "Dexron III", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Transmission Fluid", "ExtraFields": [], "PartSupplier": "SuperTech", "RequisitionHistory": []}
4	1	{"Id": 4, "Cost": 3.57, "Date": "2021-03-08T00:00:00", "Tags": [], "Files": [], "Notes": "", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Steering Fluid", "ExtraFields": [], "PartSupplier": "SuperTech", "RequisitionHistory": []}
5	1	{"Id": 5, "Cost": 3.18, "Date": "2021-03-08T00:00:00", "Tags": [], "Files": [], "Notes": "DOT 3", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Brake Fluid", "ExtraFields": [], "PartSupplier": "Prestone", "RequisitionHistory": []}
6	1	{"Id": 6, "Cost": 50.01, "Date": "2021-05-14T00:00:00", "Tags": [], "Files": [], "Notes": "Spare", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Fuel Pump", "ExtraFields": [], "PartSupplier": "Bosch", "RequisitionHistory": []}
7	1	{"Id": 7, "Cost": 30.76, "Date": "2021-06-18T00:00:00", "Tags": [], "Files": [], "Notes": "Spare", "Quantity": 1, "VehicleId": 1, "PartNumber": "", "Description": "Fuel Pump", "ExtraFields": [], "PartSupplier": "Herko", "RequisitionHistory": []}
8	1	{"Id": 8, "Cost": 22.79, "Date": "2021-07-22T00:00:00", "Tags": [], "Files": [], "Notes": "", "Quantity": 1, "VehicleId": 1, "PartNumber": "BWP 724", "Description": "Water Pump", "ExtraFields": [], "PartSupplier": "Duralast", "RequisitionHistory": []}
9	1	{"Id": 9, "Cost": 2.13, "Date": "2021-07-22T00:00:00", "Tags": [], "Files": [], "Notes": "", "Quantity": 1, "VehicleId": 1, "PartNumber": "13877", "Description": "Water Pump Gasket", "ExtraFields": [], "PartSupplier": "Fel-Pro", "RequisitionHistory": []}
10	1	{"Id": 10, "Cost": 31.46, "Date": "2021-08-05T00:00:00", "Tags": [], "Files": [], "Notes": "", "Quantity": 1, "VehicleId": 1, "PartNumber": "5S2397", "Description": "MAP Sensor", "ExtraFields": [], "PartSupplier": "WVE", "RequisitionHistory": []}
\.


--
-- Data for Name: taxrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.taxrecords (id, vehicleid, data) FROM stdin;
1	1	{"Id": 1, "Cost": 78.25, "Date": "2024-01-01T00:00:00", "Tags": [], "Files": [], "Notes": "", "VehicleId": 1, "Description": "Renewed Registration", "ExtraFields": [], "IsRecurring": false, "RecurringInterval": 12, "CustomMonthInterval": 0, "CustomMonthIntervalUnit": 1}
2	1	{"Id": 2, "Cost": 68.00, "Date": "2023-01-01T00:00:00", "Tags": [], "Files": [], "Notes": "", "VehicleId": 1, "Description": "Renewed Registration", "ExtraFields": [], "IsRecurring": false, "RecurringInterval": 12, "CustomMonthInterval": 0, "CustomMonthIntervalUnit": 1}
3	1	{"Id": 3, "Cost": 64.25, "Date": "2022-01-01T00:00:00", "Tags": [], "Files": [], "Notes": "", "VehicleId": 1, "Description": "Renewed Registration", "ExtraFields": [], "IsRecurring": false, "RecurringInterval": 12, "CustomMonthInterval": 0, "CustomMonthIntervalUnit": 1}
\.


--
-- Data for Name: tokenrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.tokenrecords (id, body, emailaddress) FROM stdin;
\.


--
-- Data for Name: upgraderecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.upgraderecords (id, vehicleid, data) FROM stdin;
9	1	{"Id": 9, "Cost": 19.19, "Date": "2021-03-23T00:00:00", "Tags": [], "Files": [], "Notes": "", "Mileage": 207930, "VehicleId": 1, "Description": "Floormats", "ExtraFields": [], "RequisitionHistory": []}
10	1	{"Id": 10, "Cost": 25.67, "Date": "2021-04-18T00:00:00", "Tags": [], "Files": [], "Notes": "MG21103", "Mileage": 208250, "VehicleId": 1, "Description": "Axle Outer Seals", "ExtraFields": [], "RequisitionHistory": []}
11	1	{"Id": 11, "Cost": 39.34, "Date": "2021-06-07T00:00:00", "Tags": [], "Files": [], "Notes": "JY Find.\\nPurchased EC-1 end caps.", "Mileage": 210750, "VehicleId": 1, "Description": "Thule Cross Bars", "ExtraFields": [], "RequisitionHistory": []}
12	1	{"Id": 12, "Cost": 127.21, "Date": "2021-06-25T00:00:00", "Tags": [], "Files": [], "Notes": "Curt 31084 + D-Ring Shackle", "Mileage": 210850, "VehicleId": 1, "Description": "Front Hitch Receiver", "ExtraFields": [], "RequisitionHistory": []}
13	1	{"Id": 13, "Cost": 50.16, "Date": "2022-05-08T00:00:00", "Tags": [], "Files": [], "Notes": "", "Mileage": 219700, "VehicleId": 1, "Description": "Stereo Upgrade", "ExtraFields": [], "RequisitionHistory": []}
\.


--
-- Data for Name: useraccessrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.useraccessrecords (userid, vehicleid) FROM stdin;
\.


--
-- Data for Name: userconfigrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.userconfigrecords (id, data) FROM stdin;
\.


--
-- Data for Name: userrecords; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.userrecords (id, username, emailaddress, password, isadmin) FROM stdin;
\.


--
-- Data for Name: vehicles; Type: TABLE DATA; Schema: app; Owner: lubelogger
--

COPY app.vehicles (id, data) FROM stdin;
1	{"Id": 1, "Make": "Jeep", "Tags": [], "Year": 1992, "Model": "Cherokee", "IsDiesel": false, "SoldDate": "03/31/2025", "UseHours": false, "SoldPrice": 0, "IsElectric": false, "ExtraFields": [], "LicensePlate": "MOMWAGON", "PurchaseDate": "01/15/2025", "ImageLocation": "/defaults/noimage.png", "PurchasePrice": 0, "DashboardMetrics": [], "OdometerOptional": false, "VehicleIdentifier": "LicensePlate", "OdometerDifference": "0", "OdometerMultiplier": "1", "HasOdometerAdjustment": false}
\.


--
-- Name: collisionrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.collisionrecords_id_seq', 34, true);


--
-- Name: gasrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.gasrecords_id_seq', 109, true);


--
-- Name: notes_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.notes_id_seq', 1, false);


--
-- Name: odometerrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.odometerrecords_id_seq', 6, true);


--
-- Name: planrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.planrecords_id_seq', 1, false);


--
-- Name: planrecordtemplates_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.planrecordtemplates_id_seq', 1, false);


--
-- Name: reminderrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.reminderrecords_id_seq', 1, false);


--
-- Name: servicerecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.servicerecords_id_seq', 22, true);


--
-- Name: supplyrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.supplyrecords_id_seq', 10, true);


--
-- Name: taxrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.taxrecords_id_seq', 3, true);


--
-- Name: tokenrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.tokenrecords_id_seq', 1, false);


--
-- Name: upgraderecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.upgraderecords_id_seq', 13, true);


--
-- Name: userrecords_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.userrecords_id_seq', 1, false);


--
-- Name: vehicles_id_seq; Type: SEQUENCE SET; Schema: app; Owner: lubelogger
--

SELECT pg_catalog.setval('app.vehicles_id_seq', 1, true);


--
-- Name: collisionrecords collisionrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.collisionrecords
    ADD CONSTRAINT collisionrecords_pkey PRIMARY KEY (id);


--
-- Name: extrafields extrafields_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.extrafields
    ADD CONSTRAINT extrafields_pkey PRIMARY KEY (id);


--
-- Name: gasrecords gasrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.gasrecords
    ADD CONSTRAINT gasrecords_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: odometerrecords odometerrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.odometerrecords
    ADD CONSTRAINT odometerrecords_pkey PRIMARY KEY (id);


--
-- Name: planrecords planrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.planrecords
    ADD CONSTRAINT planrecords_pkey PRIMARY KEY (id);


--
-- Name: planrecordtemplates planrecordtemplates_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.planrecordtemplates
    ADD CONSTRAINT planrecordtemplates_pkey PRIMARY KEY (id);


--
-- Name: reminderrecords reminderrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.reminderrecords
    ADD CONSTRAINT reminderrecords_pkey PRIMARY KEY (id);


--
-- Name: servicerecords servicerecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.servicerecords
    ADD CONSTRAINT servicerecords_pkey PRIMARY KEY (id);


--
-- Name: supplyrecords supplyrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.supplyrecords
    ADD CONSTRAINT supplyrecords_pkey PRIMARY KEY (id);


--
-- Name: taxrecords taxrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.taxrecords
    ADD CONSTRAINT taxrecords_pkey PRIMARY KEY (id);


--
-- Name: tokenrecords tokenrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.tokenrecords
    ADD CONSTRAINT tokenrecords_pkey PRIMARY KEY (id);


--
-- Name: upgraderecords upgraderecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.upgraderecords
    ADD CONSTRAINT upgraderecords_pkey PRIMARY KEY (id);


--
-- Name: useraccessrecords useraccessrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.useraccessrecords
    ADD CONSTRAINT useraccessrecords_pkey PRIMARY KEY (userid, vehicleid);


--
-- Name: userconfigrecords userconfigrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.userconfigrecords
    ADD CONSTRAINT userconfigrecords_pkey PRIMARY KEY (id);


--
-- Name: userrecords userrecords_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.userrecords
    ADD CONSTRAINT userrecords_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: app; Owner: lubelogger
--

ALTER TABLE ONLY app.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

